djangotest/djangotest/urls.py
from django.contrib import admin
from django.urls import path, include
from studentMaster.views import SchoolListView, SchoolCreateView, StudentListView, ParentListView, StudentUpdateView, \
NewRegisterView, ParentUpdateView, SchoolEditView
from django.urls import path, include

app_name = 'studentMaster'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', SchoolListView.as_view(), name='school-list'),
    path('school/<int:pk>/edit/', SchoolEditView.as_view(), name='school_edit'),  # 編集ビューのURLパターンを追加

    path('student/', StudentListView.as_view(), name='student-list'),
    path('parent/', ParentListView.as_view(), name='parent-list'),
    path('school/create/', SchoolCreateView.as_view(), name='school-create'),
    path('student/<int:pk>/edit/', StudentUpdateView.as_view(), name='student_edit'),
    path('studentMaster/', include(('studentMaster.urls', 'studentMaster'), namespace='studentMaster')),
    path('new_register/', NewRegisterView.as_view(), name='new_register'),
    path('parent/<int:pk>/edit/', ParentUpdateView.as_view(), name='parent_edit'),

  # アプリ内のurls.pyをインクルード

]

djangotest/studentMaster/urls.py
from django.urls import path
from . import views
from .views import register_student, StudentUpdateView, SchoolListView, StudentListView, NewRegisterView, ParentListView\
,ParentUpdateView
from . import views
from .views import register_view

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),  # トップページの追加
    path('school/', views.SchoolListView.as_view(), name='school-list'),
    path('school/create/', views.SchoolCreateView.as_view(), name='school-create'),
    path('register_parent/', views.register_parent, name='register_parent'),
    path('thanks/', views.thanks, name='thanks'),
    path('register_student/', register_student, name='register_student'),
    path('student/', StudentListView.as_view(), name='student-list'),
    path('student/<int:pk>/edit/', StudentUpdateView.as_view(), name='student_edit'),
    path('new_register/', NewRegisterView.as_view(), name='new_register'),
    path('parent/', ParentListView.as_view(), name='parent-list'),
    path('parent/<int:pk>/edit/', ParentUpdateView.as_view(), name='parent_edit'),
    path('add_register/', views.register_student, name='add_register'),
    path('search_parent/', views.search_parent, name='search_parent'),

]

djangotest/studentMaster/models.py
from django.db import models
from django import forms
# Create your models here.

class GenderChoices(models.TextChoices):
	Male = "男", "男"
	Female = "女", "女"
	Other = "その他", "その他"

class HowToKnowChoices(models.TextChoices):
	Ans1 = "webサイト", "webサイト"
	Ans2 = "チラシ", "チラシ"
	Ans3 = "紹介", "紹介"
	Ans4 = "兄弟が通塾している", "兄弟が通塾している"
	Ans5 = "知人からの紹介", "知人からの紹介"
	Ans6 = "看板を見た", "看板を見た"
	Ans7 = "その他", "その他"

class ClassChoices(models.TextChoices):
	Elementary = "小学校", "小学校"
	JuniorHigh = "中学校", "中学校"
	High = "高校", "高校"
	Other = "その他", "その他"

class CityChoices(models.TextChoices):
	WestTokyo = "西東京市", "西東京市"
	HigashiKurume = "東久留米市", "東久留米市"
	Niiza = "新座市", "新座市"
	Nerima = "練馬区", "練馬区"
	Kodaira = "小平市", "小平市"

class StatusChoices(models.TextChoices):
	Atend = "通塾", "通塾"
	Closed = "休塾", "休塾"
	Retired = "退塾", "退塾"
	Trial = "体験", "体験"

class SubjectChoices(models.TextChoices):
	Math = "数学", "数学"
	English = "英語", "英語"
	Science = "理科", "理科"
	Social = "社会", "社会"
	Japanese = "国語", "国語"
	Other = "その他", "その他"

class CourseChoices(models.TextChoices):
	kobetu2 = "個別指導(月2回)", "個別指導(月2回)"
	kobetu4 = "個別指導(月4回)", "個別指導(月4回)"
	kobetu8 = "個別指導(月8回)", "個別指導(月8回)"
	basic = "通い放題ベーシック", "通い放題ベーシック"
	light = "通い放題ライト", "通い放題ライト"
	mini = "通い放題ミニ", "通い放題ミニ"
	honka = "小学生本科", "小学生本科"
	sogo = "小学生総合", "小学生総合"
	robot = "ロボット教室", "ロボット教室"
	programming = "プログラミング教室", "プログラミング教室"

class GradeCoices(models.TextChoices):
	Elementary1st = "小学1年生", "小学1年生"
	Elementary2nd = "小学2年生", "小学2年生"
	Elementary3rd = "小学3年生", "小学3年生"
	Elementary4th = "小学4年生", "小学4年生"
	Elementary5th = "小学5年生", "小学5年生"
	Elementary6th = "小学6年生", "小学6年生"
	JuniorHigh1st = "中学1年生", "中学1年生"
	JuniorHigh2nd = "中学2年生", "中学2年生"
	JuniorHigh3rd = "中学3年生", "中学3年生"
	High1st = "高校1年生", "高校1年生"
	High2nd = "高校2年生", "高校2年生"
	High3rd = "高校3年生", "高校3年生"

class dbtest(models.Model):
	text = models.CharField(max_length=100)
	number = models.IntegerField()
	
	def __str__(self):
		return self.text

class School(models.Model):
	SCHOOL_TYPES = CityChoices.choices
	CLASS_TYPES = ClassChoices.choices
	school_id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=100)
	classification = models.CharField(max_length=10, choices=CLASS_TYPES)
	city = models.CharField(max_length=10, choices=SCHOOL_TYPES,blank=True)
	exam_01 = models.DateField(auto_now=False, blank=True, null=True)
	exam_02 = models.DateField(auto_now=False, blank=True, null=True)
	exam_03 = models.DateField(auto_now=False, blank=True, null=True)
	exam_04 = models.DateField(auto_now=False, blank=True, null=True)
	exam_05 = models.DateField(auto_now=False, blank=True, null=True)
	def __str__(self):
		return self.name

class Parent(models.Model):
	STATUS_TYPES = StatusChoices.choices
	HOWTOKNOW_TYPES = HowToKnowChoices.choices
	parent_id = models.AutoField(primary_key=True)
	last_name = models.CharField(max_length=100, null=True)
	first_name = models.CharField(max_length=100, null=True)
	postal_code = models.CharField(max_length=20)
	address = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	phone_number = models.CharField(max_length=100)
	status = models.CharField(max_length=10, choices=STATUS_TYPES,blank=True)
	terms = models.BooleanField(null=True)
	how_to_know = models.CharField(max_length=100,choices=HOWTOKNOW_TYPES, null=True, blank=True)

	def __str__(self):
		full_name = f'{self.last_name} {self.first_name}' if self.first_name and self.last_name else ''
		return full_name or self.first_name or self.last_name or ''


class Student(models.Model):
	GENDER_TYPES = GenderChoices.choices
	GRADE_TYPES = GradeCoices.choices
	STATUS_TYPES = StatusChoices.choices
	COURSE_TYPES = CourseChoices.choices
	student_id = models.AutoField(primary_key=True)
	last_name = models.CharField(max_length=100, null=True)
	last_name_kana = models.CharField(max_length=100, null=True)
	first_name = models.CharField(max_length=100, null=True)
	first_name_kana = models.CharField(max_length=100, null=True)
	birthday = models.DateField(auto_now=False)
	gender = models.CharField(max_length=10, choices=GENDER_TYPES)
	sibling = models.BooleanField()
	school = models.ForeignKey(School, on_delete=models.CASCADE)
	parent = models.ForeignKey(Parent, on_delete=models.CASCADE,blank=True, null=True)
	grade = models.CharField(max_length=10, choices=GRADE_TYPES,blank=True)
	status = models.CharField(max_length=10, choices=STATUS_TYPES,blank=True)
	phone_number = models.CharField(max_length=100, null=True, blank=True)
	introducer = models.CharField(max_length=100, null=True, blank=True)
	course = models.CharField(max_length=100, choices=COURSE_TYPES,blank=True)

	def __str__(self):
		return self.first_name if self.first_name and self.last_name else ''

djangotest/studentMaster/views.py
# views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView
from .models import School
from .models import Student
from .models import Parent
from django.shortcuts import render
from .forms import ParentForm
from django.http import HttpResponse
from .forms import StudentForm
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "studentMaster/home.html"

class SchoolListView(ListView):
    model = School
    template_name = 'school_list.html'
    context_object_name = 'schools'

    def get_queryset(self):
        queryset = super().get_queryset()
        filter_checked = self.request.GET.get('filter')
        if filter_checked == 'on':
            queryset = queryset.filter(classification='中学校')  # 中学校のみ絞り込み
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_checked'] = self.request.GET.get('filter')
        return context

class SchoolCreateView(CreateView):
    model = School
    template_name = 'studentMaster/school_create.html'
    fields = ['name', 'classification', 'city']
    success_url = '/school/'

class StudentListView(ListView):
    model = Student
    template_name = 'student_list.html'
    context_object_name = 'students'

    def get_queryset(self):
        queryset = super().get_queryset()
        filter_checked = self.request.GET.get('filter')
        if filter_checked == 'on':
            queryset = queryset.filter(status='A')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_checked'] = self.request.GET.get('filter')
        return context

class SchoolEditView(UpdateView):
    model = School
    fields = ['name', 'classification', 'city', 'exam_01', 'exam_02', 'exam_03', 'exam_04', 'exam_05']
    template_name = 'studentMaster/school_edit.html'
    success_url = reverse_lazy('school-list')
    
    def form_valid(self, form):
        print("Form is valid")  # フォームが有効なときにコンソールにメッセージを表示
        return super().form_valid(form)


class ParentListView(ListView):
    model = Parent
    template_name = 'parent_list.html'
    context_object_name = 'parents'

    def get_queryset(self):
        queryset = super().get_queryset()
        filter_checked = self.request.GET.get('filter')
        if filter_checked == 'on':
            queryset = queryset.filter(status='A')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_checked'] = self.request.GET.get('filter')
        return context
    
class ParentUpdateView(UpdateView):
    model = Parent
    fields = ['last_name', 'first_name', 'postal_code', 'address', 'email', 'phone_number', 'status', 'terms', 'how_to_know']
    template_name = 'studentMaster/parent_update.html'
    context_object_name = 'parent'
    success_url = reverse_lazy('parent-list')
    
def thanks(request):
    return HttpResponse("Thank you for registering!")

def register_parent(request):
    if request.method == 'POST':
        form = ParentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('studentMaster:thanks') 
    else:
        form = ParentForm()

    return render(request, 'studentMaster/register_parent.html', {'form': form})


# def register_student(request):
#     if request.method == 'POST':
#         form = StudentForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('studentMaster:thanks')
#     else:
#         form = StudentForm()

#     return render(request, 'studentMaster/add_register.html', {'form': form})

class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'studentMaster/student_update.html'
    success_url = reverse_lazy('student-list')

    def form_valid(self, form):
        print('Form is valid:', form.is_valid())
        response = super().form_valid(form)
        print('Response:', response)
        print('Redirecting to:', self.get_success_url())
        return response

    def form_invalid(self, form):
        print('Form is invalid:', form.is_valid())
        print('Form errors:', form.errors)
        return super().form_invalid(form)

from django.shortcuts import redirect
from django.views import View
from django.contrib.sessions.models import Session
from .forms import ParentForm, StudentForm, ParentSearchForm


class NewRegisterView(View):
    def get(self, request):
        student_form = StudentForm(prefix='student')
        parent_form = ParentForm(prefix='parent')
        return render(request, 'studentMaster/new_register.html', {'student_form': student_form, 'parent_form': parent_form})

    def post(self, request):
        student_form = StudentForm(request.POST, prefix='student')
        parent_form = ParentForm(request.POST, prefix='parent')
        if student_form.is_valid() and parent_form.is_valid():
            parent = parent_form.save()  # Save the parent
            student = student_form.save(commit=False)
            student.parent = parent  # Link to the student's parent field
            student.save()
            return redirect('studentMaster:thanks')

        # Print errors if there are any
        print('Student form errors:', student_form.errors)
        print('Parent form errors:', parent_form.errors)

        return render(request, 'studentMaster/new_register.html', {'student_form': student_form, 'parent_form': parent_form})



    def save_form(self, form):
        # セッションから保護者情報を取得
        session_key = form.cleaned_data.get('session_key')
        print('Session key:', session_key)
        try:
            session = Session.objects.get(session_key=session_key)
            parent_data = session.get_decoded()
            parent_form = ParentForm(parent_data, prefix='parent')
            if parent_form.is_valid():
                parent = parent_form.save()
                return parent  # 保存した Parent インスタンスを返す
            else:
                print('Parent form errors:', parent_form.errors)
        except Session.DoesNotExist:
            pass  # セッションが見つからない場合は何もしない
        return None

    # def post(self, request):
    #     student_form = StudentForm(request.POST, prefix='student')
    #     parent_form = ParentForm(request.POST, prefix='parent')
    #     if student_form.is_valid():
    #         student = student_form.save(commit=False)
    #         student.session_key = request.session.session_key
    #         parent = self.save_form(student_form)  # 保護者情報を関連付ける
    #         if parent is not None:
    #             student.parent = parent
    #             student.save()
    #             return redirect('studentMaster:thanks')
    #         else:
    #             print('Failed to save parent information.')
    #     else:
    #         print('Student form errors:', student_form.errors)

    #     return render(request, 'studentMaster/new_register.html', {'student_form': student_form, 'parent_form': parent_form})

register_view = NewRegisterView.as_view()

def search_parent(request):
    if request.method == 'POST':
        search_form = ParentSearchForm(request.POST)
        if search_form.is_valid():
            try:
                parent = Parent.objects.get(
                    last_name=search_form.cleaned_data['last_name'],
                    first_name=search_form.cleaned_data['first_name']
                )
                request.session['parent_id'] = parent.parent_id
                return redirect('studentMaster:register_student')
            except Parent.DoesNotExist:
                messages.error(request, '該当する保護者が見つかりませんでした')
                return render(request, 'studentMaster/search_parent.html', {'search_form': search_form})

    else:
        search_form = ParentSearchForm()

    return render(request, 'studentMaster/search_parent.html', {'search_form': search_form})



def register_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)  # Don't save the model yet
            parent_id = request.session.get('parent_id', None)
            if parent_id is not None:
                student.parent = Parent.objects.get(parent_id=parent_id)
            student.save()  # Now save the model
            return redirect('studentMaster:thanks')
    else:
        form = StudentForm()

    return render(request, 'studentMaster/register_student.html', {'form': form})

djangotest/studentMaster/templates/studentMaster/add_register.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<h2>生徒の登録</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">登録</button>
</form>

<h2>保護者の検索</h2>

<form method="post">
    {% csrf_token %}
    {{ search_form.as_p }}
    <button type="submit">検索</button>
</form>

djangotest/studentMaster/templates/studentMaster/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <h1>Welcome to the homepage!</h1>
    <ul>
        <li><a href="{% url 'school-list' %}">School List</a></li>
        <li><a href="{% url 'school-create' %}">Create School</a></li>
        <li><a href="{% url 'parent-list' %}">Parent_list</a></li>
        <li><a href="{% url 'student-list' %}">Student_list</a></li>
        <li><a href="{% url 'studentMaster:register_parent' %}">Register Parent</a></li>
        <li><a href="{% url 'studentMaster:new_register' %}">NewRegister</a></li>
        <li><a href="{% url 'studentMaster:search_parent' %}">AddRegister</a></li>
        <!-- 以下同様に他のリンクも追加します -->
    </ul>
</body>
</html>

djangotest/studentMaster/templates/studentMaster/new_register.html
<form method="POST" action="{% url 'studentMaster:new_register' %}">
    {% csrf_token %}
    
    <!-- Parent モデルのフィールド -->
    <div>
        保護者入力欄
    </div>
    <br>
    <div class="field-wrapper">
        <label for="{{ parent_form.last_name.id_for_label }}">保護者の苗字:</label>
        {{ parent_form.last_name }}
    </div>
    <div class="field-wrapper">
        <label for="{{ parent_form.first_name.id_for_label }}">保護者の名前:</label>
        {{ parent_form.first_name }}
    </div>
    <div class="field-wrapper">
        <label for="{{ parent_form.postal_code.id_for_label }}">保護者の郵便番号:</label>
        {{ parent_form.postal_code }}
    </div>
    <div class="field-wrapper">
        <label for="{{ parent_form.address.id_for_label }}">保護者の住所:</label>
        {{ parent_form.address }}
    </div>
    <div class="field-wrapper">
        <label for="{{ parent_form.email.id_for_label }}">保護者のメールアドレス:</label>
        {{ parent_form.email }}
    </div>
    <div class="field-wrapper">
        <label for="{{ parent_form.phone_number.id_for_label }}">保護者の電話番号:</label>
        {{ parent_form.phone_number }}
    </div>
    <div class="field-wrapper">
        <label for="{{ parent_form.terms.id_for_label }}">利用規約に同意:</label>
        {{ parent_form.terms }}
    </div>
    <div class="field-wrapper">
        <label for="{{ parent_form.how_to_know.id_for_label }}">studentMasterを知ったきっかけ:</label>
        {{ parent_form.how_to_know }}
    </div>
    <br>
    <br>
    <div>
        保護者入力欄
    </div>
    <br>

    <!-- Student モデルのフィールド -->
    <div class="field-wrapper">
        <label for="{{ student_form.last_name.id_for_label }}">生徒の苗字:</label>
        {{ student_form.last_name }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.last_name_kana.id_for_label }}">生徒の苗字（カナ）:</label>
        {{ student_form.last_name_kana }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.first_name.id_for_label }}">生徒の名前:</label>
        {{ student_form.first_name }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.first_name_kana.id_for_label }}">生徒の名前（カナ）:</label>
        {{ student_form.first_name_kana }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.prefix }}-birthday">生徒の誕生日:</label>
        <input type="date" name="{{ student_form.prefix }}-birthday" value="{{ student_form.instance.birthday|date:"Y-m-d"|default_if_none:'' }}" required>
    </div>
    
    <div class="field-wrapper">
        <label for="{{ student_form.gender.id_for_label }}">生徒の性別:</label>
        {{ student_form.gender }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.sibling.id_for_label }}">兄弟姉妹の有無:</label>
        {{ student_form.sibling }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.school.id_for_label }}">学校:</label>
        {{ student_form.school }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.grade.id_for_label }}">学年:</label>
        {{ student_form.grade }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.status.id_for_label }}">ステータス:</label>
        {{ student_form.status }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.phone_number.id_for_label }}">生徒の電話番号:</label>
        {{ student_form.phone_number }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.introducer.id_for_label }}">紹介者:</label>
        {{ student_form.introducer }}
    </div>
    <div class="field-wrapper">
        <label for="{{ student_form.course.id_for_label }}">コース:</label>
        {{ student_form.course }}
    </div>
    
    <button type="submit">登録</button>
</form>

djangotest/studentMaster/templates/studentMaster/parent_list.html
<!-- school_list.html -->
<!-- 絞り込みフォーム -->
<form method="GET" action="">
  <!-- ... -->
</form>

<!-- 学校リストの表示 -->
<table>
<thead>
  <tr>
    <th>苗字</th>
    <th>名前</th>
    <th>郵便番号</th>
    <th>住所</th>
    <th>メールアドレス</th>
    <th>電話番号</th>
    <th>ステータス</th>
    <th>規約同意</th>
    <th>BASEを知ったきっかけ</th>
    <th>操作</th> <!-- 編集ボタン用のヘッダーを追加 -->
  </tr>
</thead>
<tbody>
  {% for parent in parents %}
    <tr>
      <td>{{ parent.last_name }}</td>
      <td>{{ parent.first_name }}</td>
      <td>{{ parent.postal_code }}</td>
      <td>{{ parent.address }}</td>
      <td>{{ parent.email }}</td>
      <td>{{ parent.phone_number }}</td>
      <td>{{ parent.status }}</td>
      <td>{{ parent.terms }}</td>
      <td>{{ parent.how_to_know }}</td>
      <td>
        <a href="{% url 'parent_edit' parent.parent_id %}">編集</a> <!-- 各行に編集ボタンを配置 -->
      </td>
    </tr>
  {% endfor %}
</tbody>
</table>

djangotest/studentMaster/templates/studentMaster/parent_update.html
<!-- parent_update.html -->
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">更新</button>
</form>

djangotest/studentMaster/templates/studentMaster/register_parent.html
<form method="POST">
  {% csrf_token %}
  <div class="field-wrapper">
    <label for="{{ form.last_name.id_for_label }}">苗字:</label>
    {{ form.last_name }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.first_name.id_for_label }}">名前:</label>
    {{ form.first_name }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.postal_code.id_for_label }}">郵便番号:</label>
    {{ form.postal_code }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.address.id_for_label }}">住所:</label>
    {{ form.address }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.email.id_for_label }}">メールアドレス:</label>
    {{ form.email }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.phone_number.id_for_label }}">電話番号:</label>
    {{ form.phone_number }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.terms.id_for_label }}">利用規約に同意:</label>
    {{ form.terms }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.how_to_know.id_for_label }}">BASEを知ったきっかけ:</label>
    {{ form.how_to_know }}
  </div>
  <button type="submit">登録</button>
</form>

djangotest/studentMaster/templates/studentMaster/register_student.html
<form method="post">
  {% csrf_token %}
  <div class="field-wrapper">
    <label for="{{ form.last_name.id_for_label }}">苗字:</label>
    {{ form.last_name }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.last_name_kana.id_for_label }}">苗字（かな）:</label>
    {{ form.last_name_kana }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.first_name.id_for_label }}">名前:</label>
    {{ form.first_name }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.first_name_kana.id_for_label }}">名前（かな）:</label>
    {{ form.first_name_kana }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.birthday.id_for_label }}">誕生日:</label>
    <input type="date" name="{{ form.birthday.name }}" value="{{ form.birthday.value|default_if_none:'' }}">
  </div>
  <div class="field-wrapper">
    <label for="{{ form.gender.id_for_label }}">性別:</label>
    {{ form.gender }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.sibling.id_for_label }}">兄弟姉妹の有無:</label>
    {{ form.sibling }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.school.id_for_label }}">学校:</label>
    {{ form.school }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.grade.id_for_label }}">学年:</label>
    {{ form.grade }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.phone_number.id_for_label }}">電話番号:</label>
    {{ form.phone_number }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.introducer.id_for_label }}">紹介者:</label>
    {{ form.introducer }}
  </div>
  <div class="field-wrapper">
    <label for="{{ form.course.id_for_label }}">コース:</label>
    {{ form.course }}
  </div>
  <button type="submit">登録</button>
</form>

djangotest/studentMaster/templates/studentMaster/school_list.html
<!-- school_list.html -->
<!-- 絞り込みフォーム -->
<form method="GET" action="">
    <input type="checkbox" name="filter" id="filter" {% if filter_checked %}checked{% endif %}>
    <label for="filter">中学校のみ表示する</label>
    <button type="submit">絞り込む</button>
    {% if filter_checked %}
      <a href="?filter=">絞り込み解除</a>
    {% endif %}
  </form>
  
  <!-- 学校リストの表示 -->
  <table>
    <thead>
      <tr>
        <th>学校名</th>
        <th>区分</th>
        <th>市</th>
        <th>1学期中間</th>
        <th>1学期末</th>
        <th>2学期中間</th>
        <th>2学期末</th>
        <th>学年末</th>
        <th>編集</th>  <!-- 編集ヘッダを追加 -->
      </tr>
    </thead>
    <tbody>
      {% for school in schools %}
        <tr>
          <td>{{ school.name }}</td>
          <td>{{ school.get_classification_display }}</td>
          <td>{{ school.get_city_display }}</td>
          <td>{{ school.exam_01 }}</td>
          <td>{{ school.exam_02 }}</td>
          <td>{{ school.exam_03 }}</td>
          <td>{{ school.exam_04 }}</td>
          <td>{{ school.exam_05 }}</td>
          <td>  <!-- 編集リンクを追加 -->
            <a href="{% url 'school_edit' school.school_id %}">編集</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <!-- 学校登録リンク -->
  <a href="{% url 'school-create' %}">学校を登録する</a>
  
  